### ISSUE TITLE
Dash ornament < doesn't print correctly, prefix or postfix

### ISSUE THREAD

**Issue by paul-bayleaf** [mandovinnie/Lute-Tab#4]
The dash ornament < doesn't print correctly, prefix or postfix.  This can be seen in both sample.tab and demo.tab files.   Here is a very minimal tab file to demonstrate this. 

b
2  <a
b
2  b&<
b
e

I have a proposed fix that I will submit as a pull request.

This shows the effect before my proposed fix
[dash-ornament-before.pdf](https://github.com/mandovinnie/Lute-Tab/files/9470609/dash-ornament-before.pdf)

This is after my proposed fix
[dash-ornament-after.pdf](https://github.com/mandovinnie/Lute-Tab/files/9470614/dash-ornament-after.pdf)

**Comment by mandovinnie** [comment]
HI Paul -

 Thanks for submitting a proposed fix.  I will look at it when I get a
chance.  I don't use github for my *real* version control because I have a
very old-fashioned version control, but I will look into blending your
fixes into my code system.

   Wayne
